GET http://localhost:5000/usuarios
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTYzNjUwNzcwNywianRpIjoiOTIwOGNkODMtYzJjMC00Mjk3LTk4NmEtMDUyMTg1MzA2MzA3IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6OCwibmJmIjoxNjM2NTA3NzA3LCJleHAiOjE2MzY1MDg2MDd9.5cLwIVjbhWHiS2u2r2hVVMLpdrQN46EbDuXYYilLs5Y